
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.example;

import java_cup.runtime.*;
import java.util.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\070\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\003\003\000\002\003\003\000\002\003\003" +
    "\000\002\003\003\000\002\003\003\000\002\003\003\000" +
    "\002\003\003\000\002\003\005\000\002\003\004\000\002" +
    "\004\004\000\002\004\004\000\002\004\004\000\002\004" +
    "\004\000\002\007\003\000\002\007\004\000\002\011\003" +
    "\000\002\011\004\000\002\010\003\000\002\010\004\000" +
    "\002\010\005\000\002\010\007\000\002\012\002\000\002" +
    "\012\004\000\002\013\006\000\002\014\003\000\002\014" +
    "\004\000\002\015\006\000\002\015\007\000\002\015\006" +
    "\000\002\016\002\000\002\016\004\000\002\017\007\000" +
    "\002\017\006\000\002\006\003\000\002\006\004\000\002" +
    "\005\005\000\002\005\010\000\002\005\005\000\002\005" +
    "\006\000\002\005\005\000\002\005\004\000\002\005\005" +
    "\000\002\005\007\000\002\005\010\000\002\005\007\000" +
    "\002\005\007\000\002\005\004\000\002\005\004\000\002" +
    "\005\004\000\002\005\013\000\002\005\004\000\002\005" +
    "\004\000\002\005\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\171\000\030\004\010\005\016\006\013\007\004\010" +
    "\011\011\014\030\021\034\005\035\020\036\015\037\007" +
    "\001\002\000\036\002\ufffc\004\ufffc\005\ufffc\006\ufffc\007" +
    "\ufffc\010\ufffc\011\ufffc\030\ufffc\031\ufffc\033\ufffc\034\ufffc" +
    "\035\ufffc\036\ufffc\037\ufffc\001\002\000\030\004\010\005" +
    "\016\006\013\007\004\010\011\011\014\030\021\034\005" +
    "\035\020\036\015\037\007\001\002\000\036\002\ufff8\004" +
    "\ufff8\005\ufff8\006\ufff8\007\ufff8\010\ufff8\011\ufff8\030\ufff8" +
    "\031\ufff8\033\ufff8\034\ufff8\035\ufff8\036\ufff8\037\ufff8\001" +
    "\002\000\030\004\010\005\016\006\013\007\004\010\011" +
    "\011\014\030\021\034\005\035\020\036\015\037\007\001" +
    "\002\000\036\002\ufffe\004\ufffe\005\ufffe\006\ufffe\007\ufffe" +
    "\010\ufffe\011\ufffe\030\ufffe\031\ufffe\033\ufffe\034\ufffe\035" +
    "\ufffe\036\ufffe\037\ufffe\001\002\000\036\002\ufffb\004\ufffb" +
    "\005\ufffb\006\ufffb\007\ufffb\010\ufffb\011\ufffb\030\ufffb\031" +
    "\ufffb\033\ufffb\034\ufffb\035\ufffb\036\ufffb\037\ufffb\001\002" +
    "\000\032\002\170\004\010\005\016\006\013\007\004\010" +
    "\011\011\014\030\021\034\005\035\020\036\015\037\007" +
    "\001\002\000\036\002\ufffd\004\ufffd\005\ufffd\006\ufffd\007" +
    "\ufffd\010\ufffd\011\ufffd\030\ufffd\031\ufffd\033\ufffd\034\ufffd" +
    "\035\ufffd\036\ufffd\037\ufffd\001\002\000\036\002\ufffa\004" +
    "\ufffa\005\ufffa\006\ufffa\007\ufffa\010\ufffa\011\ufffa\030\ufffa" +
    "\031\ufffa\033\ufffa\034\ufffa\035\ufffa\036\ufffa\037\ufffa\001" +
    "\002\000\030\004\010\005\016\006\013\007\004\010\011" +
    "\011\014\030\021\034\005\035\020\036\015\037\007\001" +
    "\002\000\036\002\ufff9\004\ufff9\005\ufff9\006\ufff9\007\ufff9" +
    "\010\ufff9\011\ufff9\030\ufff9\031\ufff9\033\ufff9\034\ufff9\035" +
    "\ufff9\036\ufff9\037\ufff9\001\002\000\032\002\uffff\004\uffff" +
    "\005\uffff\006\uffff\007\uffff\010\uffff\011\uffff\030\uffff\034" +
    "\uffff\035\uffff\036\uffff\037\uffff\001\002\000\030\004\010" +
    "\005\016\006\013\007\004\010\011\011\014\030\021\034" +
    "\005\035\020\036\015\037\007\001\002\000\064\004\010" +
    "\005\016\006\013\007\004\010\011\011\014\012\027\013" +
    "\041\014\030\015\032\016\035\017\037\020\033\021\036" +
    "\022\040\024\022\025\025\026\031\027\034\030\021\031" +
    "\024\034\005\035\020\036\015\037\007\001\002\000\030" +
    "\004\010\005\016\006\013\007\004\010\011\011\014\030" +
    "\021\034\005\035\020\036\015\037\007\001\002\000\032" +
    "\004\010\005\016\006\013\007\004\010\011\011\014\030" +
    "\021\031\uffca\034\005\035\020\036\015\037\007\001\002" +
    "\000\036\002\ufff6\004\ufff6\005\ufff6\006\ufff6\007\ufff6\010" +
    "\ufff6\011\ufff6\030\ufff6\031\ufff6\033\ufff6\034\ufff6\035\ufff6" +
    "\036\ufff6\037\ufff6\001\002\000\030\004\010\005\016\006" +
    "\013\007\004\010\011\011\014\030\021\034\005\035\020" +
    "\036\015\037\007\001\002\000\004\031\160\001\002\000" +
    "\006\005\151\030\152\001\002\000\030\004\010\005\016" +
    "\006\013\007\004\010\011\011\014\030\021\034\005\035" +
    "\020\036\015\037\007\001\002\000\004\030\127\001\002" +
    "\000\030\004\010\005\016\006\013\007\004\010\011\011" +
    "\014\030\021\034\005\035\020\036\015\037\007\001\002" +
    "\000\004\030\122\001\002\000\030\004\010\005\016\006" +
    "\013\007\004\010\011\011\014\030\021\034\005\035\020" +
    "\036\015\037\007\001\002\000\004\005\117\001\002\000" +
    "\004\030\113\001\002\000\006\005\075\030\076\001\002" +
    "\000\004\030\062\001\002\000\006\005\042\030\044\001" +
    "\002\000\030\004\uffed\005\uffed\006\uffed\007\uffed\010\uffed" +
    "\011\uffed\030\uffed\034\uffed\035\uffed\036\uffed\037\uffed\001" +
    "\002\000\030\004\010\005\016\006\013\007\004\010\011" +
    "\011\014\030\021\034\005\035\020\036\015\037\007\001" +
    "\002\000\006\005\047\031\045\001\002\000\030\004\uffec" +
    "\005\uffec\006\uffec\007\uffec\010\uffec\011\uffec\030\uffec\034" +
    "\uffec\035\uffec\036\uffec\037\uffec\001\002\000\010\005\051" +
    "\031\050\032\052\001\002\000\010\005\uffef\031\uffef\032" +
    "\uffef\001\002\000\030\004\uffeb\005\uffeb\006\uffeb\007\uffeb" +
    "\010\uffeb\011\uffeb\030\uffeb\034\uffeb\035\uffeb\036\uffeb\037" +
    "\uffeb\001\002\000\010\005\uffee\031\uffee\032\uffee\001\002" +
    "\000\004\005\053\001\002\000\004\031\054\001\002\000" +
    "\030\004\uffea\005\uffea\006\uffea\007\uffea\010\uffea\011\uffea" +
    "\030\uffea\034\uffea\035\uffea\036\uffea\037\uffea\001\002\000" +
    "\032\004\010\005\016\006\013\007\004\010\011\011\014" +
    "\030\021\031\uffd9\034\005\035\020\036\015\037\007\001" +
    "\002\000\032\004\ufff1\005\ufff1\006\ufff1\007\ufff1\010\ufff1" +
    "\011\ufff1\030\ufff1\031\ufff1\034\ufff1\035\ufff1\036\ufff1\037" +
    "\ufff1\001\002\000\032\004\ufff0\005\ufff0\006\ufff0\007\ufff0" +
    "\010\ufff0\011\ufff0\030\ufff0\031\ufff0\034\ufff0\035\ufff0\036" +
    "\ufff0\037\ufff0\001\002\000\006\030\uffe6\031\uffe6\001\002" +
    "\000\006\030\062\031\uffce\001\002\000\032\004\010\005" +
    "\016\006\013\007\004\010\011\011\014\023\063\030\021" +
    "\034\005\035\020\036\015\037\007\001\002\000\030\004" +
    "\010\005\016\006\013\007\004\010\011\011\014\030\021" +
    "\034\005\035\020\036\015\037\007\001\002\000\032\004" +
    "\010\005\016\006\013\007\004\010\011\011\014\030\021" +
    "\033\065\034\005\035\020\036\015\037\007\001\002\000" +
    "\030\004\010\005\016\006\013\007\004\010\011\011\014" +
    "\030\021\034\005\035\020\036\015\037\007\001\002\000" +
    "\032\004\010\005\016\006\013\007\004\010\011\011\014" +
    "\030\021\031\067\034\005\035\020\036\015\037\007\001" +
    "\002\000\006\030\uffe4\031\uffe4\001\002\000\004\031\071" +
    "\001\002\000\006\030\uffe3\031\uffe3\001\002\000\032\004" +
    "\010\005\016\006\013\007\004\010\011\011\014\030\021" +
    "\031\073\034\005\035\020\036\015\037\007\001\002\000" +
    "\006\030\uffe2\031\uffe2\001\002\000\006\030\uffe5\031\uffe5" +
    "\001\002\000\004\030\107\001\002\000\006\030\uffe9\031" +
    "\uffe9\001\002\000\006\030\101\031\100\001\002\000\030" +
    "\004\010\005\016\006\013\007\004\010\011\011\014\030" +
    "\021\034\005\035\020\036\015\037\007\001\002\000\004" +
    "\005\103\001\002\000\006\030\uffe8\031\uffe8\001\002\000" +
    "\030\004\010\005\016\006\013\007\004\010\011\011\014" +
    "\030\021\034\005\035\020\036\015\037\007\001\002\000" +
    "\004\031\105\001\002\000\006\030\uffe7\031\uffe7\001\002" +
    "\000\032\004\010\005\016\006\013\007\004\010\011\011" +
    "\014\030\021\031\uffd4\034\005\035\020\036\015\037\007" +
    "\001\002\000\006\030\uffe9\031\uffe9\001\002\000\006\030" +
    "\101\031\111\001\002\000\030\004\010\005\016\006\013" +
    "\007\004\010\011\011\014\030\021\034\005\035\020\036" +
    "\015\037\007\001\002\000\032\004\010\005\016\006\013" +
    "\007\004\010\011\011\014\030\021\031\uffd3\034\005\035" +
    "\020\036\015\037\007\001\002\000\006\030\uffe9\031\uffe9" +
    "\001\002\000\006\030\101\031\115\001\002\000\030\004" +
    "\010\005\016\006\013\007\004\010\011\011\014\030\021" +
    "\034\005\035\020\036\015\037\007\001\002\000\032\004" +
    "\010\005\016\006\013\007\004\010\011\011\014\030\021" +
    "\031\uffd1\034\005\035\020\036\015\037\007\001\002\000" +
    "\030\004\010\005\016\006\013\007\004\010\011\011\014" +
    "\030\021\034\005\035\020\036\015\037\007\001\002\000" +
    "\004\031\uffd5\001\002\000\004\031\uffcc\001\002\000\006" +
    "\030\uffe9\031\uffe9\001\002\000\006\030\101\031\124\001" +
    "\002\000\030\004\010\005\016\006\013\007\004\010\011" +
    "\011\014\030\021\034\005\035\020\036\015\037\007\001" +
    "\002\000\032\004\010\005\016\006\013\007\004\010\011" +
    "\011\014\030\021\031\uffd2\034\005\035\020\036\015\037" +
    "\007\001\002\000\032\004\010\005\016\006\013\007\004" +
    "\010\011\011\014\030\021\031\uffd6\034\005\035\020\036" +
    "\015\037\007\001\002\000\006\030\uffe1\031\uffe1\001\002" +
    "\000\006\030\133\031\132\001\002\000\006\030\uffe0\031" +
    "\uffe0\001\002\000\004\030\141\001\002\000\004\005\134" +
    "\001\002\000\030\004\010\005\016\006\013\007\004\010" +
    "\011\011\014\030\021\034\005\035\020\036\015\037\007" +
    "\001\002\000\032\004\010\005\016\006\013\007\004\010" +
    "\011\011\014\030\021\031\136\034\005\035\020\036\015" +
    "\037\007\001\002\000\006\030\uffde\031\uffde\001\002\000" +
    "\004\031\140\001\002\000\006\030\uffdf\031\uffdf\001\002" +
    "\000\030\004\010\005\016\006\013\007\004\010\011\011" +
    "\014\030\021\034\005\035\020\036\015\037\007\001\002" +
    "\000\030\004\010\005\016\006\013\007\004\010\011\011" +
    "\014\030\021\034\005\035\020\036\015\037\007\001\002" +
    "\000\032\004\010\005\016\006\013\007\004\010\011\011" +
    "\014\030\021\031\144\034\005\035\020\036\015\037\007" +
    "\001\002\000\030\004\010\005\016\006\013\007\004\010" +
    "\011\011\014\030\021\034\005\035\020\036\015\037\007" +
    "\001\002\000\032\004\010\005\016\006\013\007\004\010" +
    "\011\011\014\030\021\031\uffcd\034\005\035\020\036\015" +
    "\037\007\001\002\000\030\004\010\005\016\006\013\007" +
    "\004\010\011\011\014\030\021\034\005\035\020\036\015" +
    "\037\007\001\002\000\032\004\010\005\016\006\013\007" +
    "\004\010\011\011\014\030\021\031\uffd7\034\005\035\020" +
    "\036\015\037\007\001\002\000\004\031\uffd8\001\002\000" +
    "\030\004\010\005\016\006\013\007\004\010\011\011\014" +
    "\030\021\034\005\035\020\036\015\037\007\001\002\000" +
    "\004\005\153\001\002\000\004\005\047\001\002\000\006" +
    "\005\051\031\155\001\002\000\030\004\010\005\016\006" +
    "\013\007\004\010\011\011\014\030\021\034\005\035\020" +
    "\036\015\037\007\001\002\000\032\004\010\005\016\006" +
    "\013\007\004\010\011\011\014\030\021\031\uffda\034\005" +
    "\035\020\036\015\037\007\001\002\000\004\031\uffdb\001" +
    "\002\000\036\002\ufff7\004\ufff7\005\ufff7\006\ufff7\007\ufff7" +
    "\010\ufff7\011\ufff7\030\ufff7\031\ufff7\033\ufff7\034\ufff7\035" +
    "\ufff7\036\ufff7\037\ufff7\001\002\000\032\004\010\005\016" +
    "\006\013\007\004\010\011\011\014\030\021\031\uffcf\034" +
    "\005\035\020\036\015\037\007\001\002\000\004\031\uffcb" +
    "\001\002\000\032\004\010\005\016\006\013\007\004\010" +
    "\011\011\014\030\021\031\uffdd\034\005\035\020\036\015" +
    "\037\007\001\002\000\004\031\uffdc\001\002\000\032\004" +
    "\010\005\016\006\013\007\004\010\011\011\014\030\021" +
    "\031\uffd0\034\005\035\020\036\015\037\007\001\002\000" +
    "\036\002\ufff4\004\ufff4\005\ufff4\006\ufff4\007\ufff4\010\ufff4" +
    "\011\ufff4\030\ufff4\031\ufff4\033\ufff4\034\ufff4\035\ufff4\036" +
    "\ufff4\037\ufff4\001\002\000\036\002\ufff3\004\ufff3\005\ufff3" +
    "\006\ufff3\007\ufff3\010\ufff3\011\ufff3\030\ufff3\031\ufff3\033" +
    "\ufff3\034\ufff3\035\ufff3\036\ufff3\037\ufff3\001\002\000\004" +
    "\002\000\001\002\000\032\002\001\004\001\005\001\006" +
    "\001\007\001\010\001\011\001\030\001\034\001\035\001" +
    "\036\001\037\001\001\002\000\036\002\ufff2\004\ufff2\005" +
    "\ufff2\006\ufff2\007\ufff2\010\ufff2\011\ufff2\030\ufff2\031\ufff2" +
    "\033\ufff2\034\ufff2\035\ufff2\036\ufff2\037\ufff2\001\002\000" +
    "\036\002\ufff5\004\ufff5\005\ufff5\006\ufff5\007\ufff5\010\ufff5" +
    "\011\ufff5\030\ufff5\031\ufff5\033\ufff5\034\ufff5\035\ufff5\036" +
    "\ufff5\037\ufff5\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\171\000\010\002\011\003\016\004\005\001\001\000" +
    "\002\001\001\000\006\003\172\004\005\001\001\000\002" +
    "\001\001\000\006\003\171\004\005\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\003\170\004\005\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\003\166\004" +
    "\005\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\003\165\004\005\001\001\000\010\003\022\004\005\005" +
    "\025\001\001\000\010\003\055\004\005\007\164\001\001" +
    "\000\010\003\162\004\005\006\161\001\001\000\002\001" +
    "\001\000\010\003\055\004\005\007\160\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\003\145\004\005\001" +
    "\001\000\002\001\001\000\010\003\055\004\005\007\125" +
    "\001\001\000\002\001\001\000\006\003\120\004\005\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\014\060\015\057\001\001\000\004\010\042\001" +
    "\001\000\002\001\001\000\010\003\055\004\005\007\054" +
    "\001\001\000\004\011\045\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\003\056\004\005\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\015\073\001" +
    "\001\000\006\003\063\004\005\001\001\000\010\003\055" +
    "\004\005\007\071\001\001\000\010\003\055\004\005\007" +
    "\065\001\001\000\006\003\067\004\005\001\001\000\006" +
    "\003\056\004\005\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\003\056\004\005\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\012\076\001\001\000\004\013\101\001\001\000\010" +
    "\003\055\004\005\007\105\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\003\103\004\005\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\003\056\004\005\001" +
    "\001\000\004\012\107\001\001\000\004\013\101\001\001" +
    "\000\010\003\055\004\005\007\111\001\001\000\006\003" +
    "\056\004\005\001\001\000\004\012\113\001\001\000\004" +
    "\013\101\001\001\000\010\003\055\004\005\007\115\001" +
    "\001\000\006\003\056\004\005\001\001\000\006\003\117" +
    "\004\005\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\012\122\001\001\000\004\013\101\001\001\000\010" +
    "\003\055\004\005\007\124\001\001\000\006\003\056\004" +
    "\005\001\001\000\006\003\056\004\005\001\001\000\004" +
    "\016\127\001\001\000\004\017\130\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\003\134" +
    "\004\005\001\001\000\006\003\136\004\005\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\003\141\004\005\001\001\000\010\003\055\004\005\007" +
    "\142\001\001\000\006\003\056\004\005\001\001\000\010" +
    "\003\055\004\005\007\144\001\001\000\006\003\056\004" +
    "\005\001\001\000\006\003\146\004\005\001\001\000\006" +
    "\003\147\004\005\001\001\000\002\001\001\000\006\003" +
    "\156\004\005\001\001\000\002\001\001\000\004\011\153" +
    "\001\001\000\002\001\001\000\010\003\055\004\005\007" +
    "\155\001\001\000\006\003\056\004\005\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\003\056\004\005\001" +
    "\001\000\002\001\001\000\010\003\162\004\005\006\163" +
    "\001\001\000\002\001\001\000\006\003\056\004\005\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // program ::= program expr 
            {
              ProgramNode RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ProgramNode p = (ProgramNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ASTNode e = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                p.addExpression(e);
                RESULT = p;
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ProgramNode start_val = (ProgramNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // program ::= expr 
            {
              ProgramNode RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ASTNode e = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                ProgramNode prog = new ProgramNode();
                prog.addExpression(e);
                RESULT = prog;
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // expr ::= NUMBER 
            {
              ASTNode RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object n = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new NumberNode((Number)n); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // expr ::= STRING 
            {
              ASTNode RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new StringNode(s); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // expr ::= CHARACTER 
            {
              ASTNode RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CharacterNode(c); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // expr ::= TRUE 
            {
              ASTNode RESULT =null;
		 RESULT = new BooleanNode(true); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // expr ::= FALSE 
            {
              ASTNode RESULT =null;
		 RESULT = new BooleanNode(false); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // expr ::= IDENTIFIER 
            {
              ASTNode RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new IdentifierNode(id); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // expr ::= quoted 
            {
              ASTNode RESULT =null;
		int qleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int qright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ASTNode q = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = q; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // expr ::= LPAREN list_contents RPAREN 
            {
              ASTNode RESULT =null;
		int lcleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lcright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ASTNode lc = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = lc; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // expr ::= LPAREN RPAREN 
            {
              ASTNode RESULT =null;
		 RESULT = new ListNode(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // quoted ::= QUOTE_CHAR expr 
            {
              ASTNode RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ASTNode e = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new QuoteNode(e); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("quoted",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // quoted ::= BACKQUOTE expr 
            {
              ASTNode RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ASTNode e = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new QuasiquoteNode(e); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("quoted",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // quoted ::= COMMA expr 
            {
              ASTNode RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ASTNode e = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new UnquoteNode(e); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("quoted",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // quoted ::= COMMA_AT expr 
            {
              ASTNode RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ASTNode e = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new UnquoteSplicingNode(e); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("quoted",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // body ::= expr 
            {
              java.util.List<ASTNode> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ASTNode e = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
             List<ASTNode> l = new ArrayList<>();
             l.add(e);
             RESULT = l;
         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("body",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // body ::= body expr 
            {
              java.util.List<ASTNode> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		java.util.List<ASTNode> l = (java.util.List<ASTNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ASTNode e = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
             l.add(e);
             RESULT = l;
         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("body",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // id_list ::= IDENTIFIER 
            {
              java.util.List<String> RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                List<String> l = new ArrayList<>();
                l.add(id);
                RESULT = l;
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("id_list",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // id_list ::= id_list IDENTIFIER 
            {
              java.util.List<String> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		java.util.List<String> l = (java.util.List<String>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                l.add(id);
                RESULT = l;
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("id_list",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // formals ::= IDENTIFIER 
            {
              FormalsNode RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new FormalsNode(id); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("formals",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // formals ::= LPAREN RPAREN 
            {
              FormalsNode RESULT =null;
		 RESULT = new FormalsNode(new ArrayList<String>()); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("formals",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // formals ::= LPAREN id_list RPAREN 
            {
              FormalsNode RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		java.util.List<String> list = (java.util.List<String>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new FormalsNode(list); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("formals",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // formals ::= LPAREN id_list DOT IDENTIFIER RPAREN 
            {
              FormalsNode RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		java.util.List<String> list = (java.util.List<String>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int restleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int restright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String rest = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new FormalsNode(list, rest); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("formals",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // bindings ::= 
            {
              java.util.List<ASTNode> RESULT =null;
		 RESULT = new ArrayList<ASTNode>(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bindings",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // bindings ::= bindings binding 
            {
              java.util.List<ASTNode> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		java.util.List<ASTNode> l = (java.util.List<ASTNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		BindingNode b = (BindingNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 l.add(b); RESULT = l; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bindings",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // binding ::= LPAREN IDENTIFIER expr RPAREN 
            {
              BindingNode RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ASTNode val = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new BindingNode(id, val); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("binding",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // cond_clauses ::= cond_clause 
            {
              java.util.List<ASTNode> RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ASTNode c = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                     List<ASTNode> l = new ArrayList<>();
                     l.add(c);
                     RESULT = l;
                 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cond_clauses",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // cond_clauses ::= cond_clauses cond_clause 
            {
              java.util.List<ASTNode> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		java.util.List<ASTNode> l = (java.util.List<ASTNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ASTNode c = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                     l.add(c);
                     RESULT = l;
                 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cond_clauses",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // cond_clause ::= LPAREN expr body RPAREN 
            {
              ASTNode RESULT =null;
		int testleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int testright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ASTNode test = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		java.util.List<ASTNode> b = (java.util.List<ASTNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new CondClauseNode(test, b); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cond_clause",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // cond_clause ::= LPAREN expr ARROW expr RPAREN 
            {
              ASTNode RESULT =null;
		int testleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int testright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		ASTNode test = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int funcleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int funcright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ASTNode func = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new CondArrowNode(test, func); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cond_clause",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // cond_clause ::= LPAREN ELSE body RPAREN 
            {
              ASTNode RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		java.util.List<ASTNode> b = (java.util.List<ASTNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new CondElseNode(b); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cond_clause",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // do_bindings ::= 
            {
              java.util.List<ASTNode> RESULT =null;
		 RESULT = new ArrayList<ASTNode>(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("do_bindings",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // do_bindings ::= do_bindings do_binding 
            {
              java.util.List<ASTNode> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		java.util.List<ASTNode> l = (java.util.List<ASTNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		DoBindingNode b = (DoBindingNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 l.add(b); RESULT = l; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("do_bindings",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // do_binding ::= LPAREN IDENTIFIER expr expr RPAREN 
            {
              DoBindingNode RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int initleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int initright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ASTNode init = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int stepleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int stepright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ASTNode step = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new DoBindingNode(id, init, step); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("do_binding",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // do_binding ::= LPAREN IDENTIFIER expr RPAREN 
            {
              DoBindingNode RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int initleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int initright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ASTNode init = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new DoBindingNode(id, init, null); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("do_binding",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // list_rest ::= expr 
            {
              java.util.LinkedList<ASTNode> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ASTNode e = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                  LinkedList<ASTNode> list = new LinkedList<>();
                  list.add(e);
                  RESULT = list;
              
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_rest",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // list_rest ::= expr list_rest 
            {
              java.util.LinkedList<ASTNode> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ASTNode e = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int restleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int restright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		java.util.LinkedList<ASTNode> rest = (java.util.LinkedList<ASTNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                  rest.addFirst(e);
                  RESULT = rest;
              
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_rest",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // list_contents ::= DEFINE IDENTIFIER expr 
            {
              ASTNode RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ASTNode value = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new DefineNode(name, value); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_contents",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // list_contents ::= DEFINE LPAREN IDENTIFIER id_list RPAREN body 
            {
              ASTNode RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int argsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int argsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		java.util.List<String> args = (java.util.List<String>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		java.util.List<ASTNode> b = (java.util.List<ASTNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new DefineNode(name, new LambdaNode(new FormalsNode(args), b)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_contents",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // list_contents ::= LAMBDA formals body 
            {
              ASTNode RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		FormalsNode f = (FormalsNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		java.util.List<ASTNode> b = (java.util.List<ASTNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new LambdaNode(f, b); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_contents",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // list_contents ::= IF expr expr expr 
            {
              ASTNode RESULT =null;
		int testleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int testright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ASTNode test = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int thenleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int thenright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ASTNode then = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int elsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int elsright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ASTNode els = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new IfNode(test, then, els); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_contents",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // list_contents ::= IF expr expr 
            {
              ASTNode RESULT =null;
		int testleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int testright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ASTNode test = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int thenleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int thenright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ASTNode then = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new IfNode(test, then, new BooleanNode(false)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_contents",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // list_contents ::= BEGIN body 
            {
              ASTNode RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		java.util.List<ASTNode> b = (java.util.List<ASTNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new BeginNode(b); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_contents",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // list_contents ::= SET IDENTIFIER expr 
            {
              ASTNode RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ASTNode value = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new SetNode(name, value); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_contents",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // list_contents ::= LET LPAREN bindings RPAREN body 
            {
              ASTNode RESULT =null;
		int bindsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int bindsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		java.util.List<ASTNode> binds = (java.util.List<ASTNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		java.util.List<ASTNode> b = (java.util.List<ASTNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new LetNode(binds, b); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_contents",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // list_contents ::= LET IDENTIFIER LPAREN bindings RPAREN body 
            {
              ASTNode RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int bindsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int bindsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		java.util.List<ASTNode> binds = (java.util.List<ASTNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		java.util.List<ASTNode> b = (java.util.List<ASTNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new NamedLetNode(name, binds, b); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_contents",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // list_contents ::= LET_STAR LPAREN bindings RPAREN body 
            {
              ASTNode RESULT =null;
		int bindsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int bindsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		java.util.List<ASTNode> binds = (java.util.List<ASTNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		java.util.List<ASTNode> b = (java.util.List<ASTNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new LetStarNode(binds, b); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_contents",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // list_contents ::= LETREC LPAREN bindings RPAREN body 
            {
              ASTNode RESULT =null;
		int bindsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int bindsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		java.util.List<ASTNode> binds = (java.util.List<ASTNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		java.util.List<ASTNode> b = (java.util.List<ASTNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new LetRecNode(binds, b); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_contents",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // list_contents ::= AND body 
            {
              ASTNode RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		java.util.List<ASTNode> b = (java.util.List<ASTNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new AndNode(b); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_contents",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // list_contents ::= OR body 
            {
              ASTNode RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		java.util.List<ASTNode> b = (java.util.List<ASTNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new OrNode(b); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_contents",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // list_contents ::= COND cond_clauses 
            {
              ASTNode RESULT =null;
		int clausesleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int clausesright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		java.util.List<ASTNode> clauses = (java.util.List<ASTNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CondNode(clauses); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_contents",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // list_contents ::= DO LPAREN do_bindings RPAREN LPAREN expr body RPAREN body 
            {
              ASTNode RESULT =null;
		int bindsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int bindsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		java.util.List<ASTNode> binds = (java.util.List<ASTNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int testleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int testright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		ASTNode test = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int btestleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int btestright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		java.util.List<ASTNode> btest = (java.util.List<ASTNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		java.util.List<ASTNode> b = (java.util.List<ASTNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new DoNode(binds, test, btest, b); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_contents",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // list_contents ::= DELAY expr 
            {
              ASTNode RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ASTNode e = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new DelayNode(e); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_contents",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // list_contents ::= expr list_rest 
            {
              ASTNode RESULT =null;
		int funcleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int funcright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ASTNode func = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int argsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int argsright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		java.util.LinkedList<ASTNode> args = (java.util.LinkedList<ASTNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                      RESULT = new ProcedureCallNode(func, new ArrayList<>(args));
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_contents",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // list_contents ::= expr 
            {
              ASTNode RESULT =null;
		int funcleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int funcright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ASTNode func = (ASTNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new ProcedureCallNode(func, new ArrayList<>()); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_contents",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
