
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int AND = 18;
  public static final int ELSE = 17;
  public static final int RPAREN = 23;
  public static final int OR = 19;
  public static final int DEFINE = 8;
  public static final int CHARACTER = 5;
  public static final int IDENTIFIER = 3;
  public static final int TRUE = 6;
  public static final int IF = 10;
  public static final int LPAREN = 22;
  public static final int DO = 20;
  public static final int BEGIN = 11;
  public static final int DELAY = 21;
  public static final int LET_STAR = 14;
  public static final int STRING = 4;
  public static final int COMMA = 28;
  public static final int EOF = 0;
  public static final int NUMBER = 2;
  public static final int SET = 12;
  public static final int QUOTE_CHAR = 26;
  public static final int LETREC = 15;
  public static final int FALSE = 7;
  public static final int COMMA_AT = 29;
  public static final int ARROW = 25;
  public static final int DOT = 24;
  public static final int error = 1;
  public static final int LET = 13;
  public static final int COND = 16;
  public static final int BACKQUOTE = 27;
  public static final int LAMBDA = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMBER",
  "IDENTIFIER",
  "STRING",
  "CHARACTER",
  "TRUE",
  "FALSE",
  "DEFINE",
  "LAMBDA",
  "IF",
  "BEGIN",
  "SET",
  "LET",
  "LET_STAR",
  "LETREC",
  "COND",
  "ELSE",
  "AND",
  "OR",
  "DO",
  "DELAY",
  "LPAREN",
  "RPAREN",
  "DOT",
  "ARROW",
  "QUOTE_CHAR",
  "BACKQUOTE",
  "COMMA",
  "COMMA_AT"
  };
}

